backend/routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(/**
 *
 */ ['middleware' => ['CheckVeri']], function () {
    Route::get('/', function() {
        return redirect('admin-dashboard');
    });
    Route::get('/admin-dashboard','DashboardController@index')->name('admin-dashboard');
    Route::get('/api-show-task-today','DashboardController@showMyTaskToday');

    Route::resource('/user-profile','UserController');
    Route::resource('/project','ProjectController');

    //project
    Route::get('/add-member/{id}','ProjectController@addMember')->name('project.addMember');
    Route::post('/createMember','ProjectController@createMember')->name('project.createMember');
    Route::get('/project-delete','ProjectController@destroyProject')->name('project-delete');
    Route::get('/api-show-count-project-task','ProjectController@apiCountTaskProject')->name('api-show-count-project-task');
    //download
    Route::post('/download','DownloadController@download')->name('download');

    Route::resource('/project-item','ProjectItemController');

    //task
    Route::resource('/project-task','TaskController');
    Route::get('/my-task','TaskController@myTask')->name('my-task');
    Route::get('/add-member-task/{id}','TaskController@addMember')->name('add-member-task');
    Route::post('/createMemberSubtask','TaskController@createMemberSubTask')->name('createMemberSubTask');
    Route::post('/update-task','AdminTaskController@updateTask')->name('update-task');


    Route::get('/show-task','TaskController@apiShowTask')->name('api.ShowTask');

    Route::post('update-status-task','ProjectController@UpdateProcess')->name('project.update-process-task');

    Route::get('/show-my-task-data','TaskController@showMyTaskData')->name('api.show-my-task-data');

    Route::get('/show-data-project','ProjectController@showData')->name('api.project.showData');

    Route::get('/apiShowDetailTask',"TaskController@apiShowDetailTask")->name('apiShowDetailTask');
    //calendar

    Route::get('/show-calendar-my-task','TaskController@calendarMyTask')->name('show-calendar-my-task');
    Route::get('/api-show-my-task','TaskController@apiShowMyTask')->name('api.ShowMyTask');
    Route::get('/api-search-my-task','TaskController@apiSearchMyTask')->name('api.SearchMyTask');
    Route::get('/search-my-task','TaskController@searchMyTaskCalendar')->name('searchMyTaskCalendar');

    //only admin
    Route::resource('/admin-task','AdminTaskController');
    Route::get('/api-show-all-task','AdminTaskController@showAllTask')->name('api-show-all-task');
    Route::get('/calendar-admin-task','AdminTaskController@calendarTaskAdmin')->name('calendar-admin-task');
    Route::get('/api-show-admin-task','AdminTaskController@apiShowAdminCalendar')->name('api.ShowAdminTask');
    Route::get('/search-calendar-admin','AdminTaskController@searchCalendarAdmin')->name('search.CalendarAdmin');
    Route::get('/show-all-user','UserController@showUser')->name('show-all-user');
    Route::get('/api-task-due-date','AdminTaskController@showTaskDueDate')->name('api-task-due-date');


    //Report
    Route::get('/report','ReportController@index')->name('report.index');
    Route::get('/report-apiShowCountTask','ReportController@apiShowCountTask')->name('report.apiShowCountTask');

    //update task by api
    Route::get('/api-update-task','AdminTaskController@apiUpdateTask')->name('apiUpdateTask');

    //company
    Route::resource('/company','AdminCompanyController');
    Route::get('/show-data-company','AdminCompanyController@showData')->name('show-data-company');
    Route::get('/company-delete','AdminCompanyController@destroyCompany')->name('destroy-company');

    //user
    Route::resource('/admin-user','AdminUserController');
    Route::get('/show-data-user','AdminUserController@showData')->name('show-user-company');
    Route::get('/admin-user-confirm/{id}','AdminUserController@updateUser')->name('updateUser');
    Route::get('/user-delete','AdminUserController@userDelete')->name('user-delete');
    Route::post('/user-delete-all','AdminUserController@userDeleteAll')->name('user-delete-all');
    Route::get('/upgrade-manager/{id}','AdminUserController@upgradeManger')->name('upgrade-manager');
    Route::get('/upgrade-user/{id}','AdminUserController@updateMember')->name('upgrade-user');

    //grant chart
    Route::resource('/grant-chart',"GrantChartController");
    //api grant chart
    Route::get('/api-grant-chart','GrantChartController@apiGrantChart')->name('api-grant-chart');
    Route::get('/search-gantt-chart','GrantChartController@searchGantt')->name('search-gantt-chart');
    Route::get('/api-search-gantt-chart','GrantChartController@apiSearchGanttChart')->name('api-search-gantt-chart');

    //delete sub task
    Route::get('/delete-sub-task/{id}','AdminTaskController@deleteSubTask')->name('delete-sub-task');

    //gantt
    Route::get('/api-pie-chart','AdminChartController@apiPieChart')->name('api-pie-chart');

    //project more
    Route::get('/project-more', function (){return view('admin.project.more');})->name('project.more');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/error-not-verify', function (){
   return view('errors.500');
});

Route::get('change-language/{locale}', 'HomeController@changeLanguage')->name('user.change-language');

Route::post('/uploads-file',function (){
    return "OKKOKOKOK";
});

backend/app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
    'c_code',
    'pName',
    'psDate',
    'peDate',
    'pType',
    'pContents',
    'pAmount',
    ];

}

backend/app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\Eloquent\ProjectEloquentRepository;
use App\Repositories\Eloquent\ProjectItemEloquentRepository;
use App\Repositories\Eloquent\CompanyEloquentRepository;
use App\Repositories\Eloquent\AttachmentEloquentRepository;
use App\Repositories\Eloquent\UserEloquentRepository;
use App\Repositories\Eloquent\TaskEloquentRepository;
use Auth;
use Illuminate\Pagination\Paginator;
use App\Models\TaskM;
use Input;
use Yajra\DataTables\DataTables;
use App\User;
use Session;
use App;
use Config;
class ProjectController extends Controller
{
    private $projectRepository;
    private $projectItemRepository;
    private $companyRepository;
    private $attachmentRepository;
    private $userRepository;
    private $taskRepository;

    function __construct(
        ProjectEloquentRepository $projectRepository,
        CompanyEloquentRepository $companyRepository,
        AttachmentEloquentRepository $attachmentRepository,
        UserEloquentRepository $userRepository,
        ProjectItemEloquentRepository $projectItemRepository,
        TaskEloquentRepository $taskRepository
    )
    {
        $this->projectRepository = $projectRepository;
        $this->companyRepository = $companyRepository;
        $this->attachmentRepository = $attachmentRepository;
        $this->userRepository = $userRepository;
        $this->projectItemRepository = $projectItemRepository;
        $this->taskRepository = $taskRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        App::setLocale(Session::get('locale'));
        $locale = Config::get('app.locale');
        if ($locale == null) {
            $locale = 'en';
        }
        return view('admin.project.index',compact('locale'));
    }

    public function showData()
    {
        $checkisAdmin = Auth::user()->is_Admin;
        $project = $this->projectRepository->showData();
        $userId = Auth::user()->id;
        $project_user = $this->projectRepository->showProjectOnlyUser($userId);
        $encrypter = app('Illuminate\Encryption\Encrypter');
        $token = $encrypter->encrypt(csrf_token());
        if ($checkisAdmin === 1) {
            return Datatables::of($project)
                ->addColumn('action', function ($project) use ($token) {
                    return '
                <a class="btn btn-sm btn-info btn-round btn-register" style="margin-right:1em" href="/project/' . $project->id . '"> <i class="fas fa-eye"></i></a>
                <a class="btn  btn-sm btn-success btn-register" href="/project/' . $project->id . '/edit"> <i class="far fa-edit"></i></a>
                <a class="btn btn-sm btn-danger btn-register "style="margin-left:1em"  href="javascript:void(0);" onclick="return confirmDelete(' . $project->id . ')"> <i class="fas fa-trash-alt"></i></a>
                 <form action="project-delete" method="get" id="frm_delete_' . $project->id . '">
                    <input type="hidden" name="id" value='.$project->id.'>
                </form>';
                })
                ->make(true);
        } else {
            return Datatables::of($project_user)
                ->addColumn('action', function ($project) use ($token) {
                    return '
                <a class="btn btn-sm btn-info btn-round btn-register" href="/project/' . $project->id . '"> <i class="fas fa-eye"></i></a>
               ';
                })
                ->make(true);
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company_id = Auth::user()->c_code;
        $user = User::where('c_code',$company_id)->where('u_auth',1)->get();
        $company = $this->companyRepository->all();
        return view('admin.project.create', compact(['company','user']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //create project
        $project = $this->projectRepository->create($request->all());

        $user = Auth::user();

        //upload attachment file
        if ($request->hasFile('a_code')) {
            $excel = $request->file('a_code')->store('public/documents');
            $url_excel = $excel;
            $attachment = $this->attachmentRepository->create([
                'c_code' => $user->c_code,
                'p_code' => $project->id,
                'a_file' => $request->file('a_code')->getClientOriginalName(),
                'a_fileName' => $url_excel,
                'a_date' => date("Y-m-d"),
                'user_id' => $user->id
            ]);
        }
        $arrUser = $request->get('arrUser');

        //insert
        foreach ($arrUser as $key => $item) {
            $addMember = $this->projectItemRepository->create([
                'u_id' => $item,
                'c_code' => $project->c_code,
                'p_name_item' => $project->pName,
                'pu_Auth' => 1,
                'p_code' => $project->id
            ]);
        }
//         return redirect()->back()->with('message', 'Create successful!');
        return redirect()->route('project.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Auth::user();

        $project = $this->projectRepository->find($id);

        $project_item = $this->projectItemRepository->findProjectItem($project->id);
        $showTask = $this->projectRepository->showTask($id, $user);
//        return $showTask;
        $attachment = $this->attachmentRepository->findByField('p_code', $project->id);
        return view('admin.project.show', compact(['project', 'project_item', 'attachment', 'id', 'showTask']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = $this->companyRepository->all();
        $project = $this->projectRepository->find($id);

        return view('admin.project.edit', compact(['project', 'company']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = Auth::user();

        //upload attachment file
        if ($request->hasFile('a_code')) {
            $excel = $request->file('a_code')->store('public/documents');
            $url_excel = $excel;
            $attachment = $this->attachmentRepository->create([
                'c_code' => $user->c_code,
                'p_code' => $id,
                'a_file' => $url_excel,
                'a_fileName' => $request->file('a_code')->getClientOriginalName(),
                'a_date' => date("Y-m-d"),
                'user_id' => $user->id
            ]);
        }

        $project = $this->projectRepository->update($request->all(), $id);
        return redirect()->route('project.index')->with('message', 'Update successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = $this->projectRepository->delete($id);
        return redirect()->back()->with('message', 'Delete successful!');
    }

    //** return view addmember */
    public function addMember($id)
    {
        $company_id = Auth::user()->c_code;
        $user = $this->userRepository->findByField('c_code', $company_id);
        $check_member = $this->projectRepository->checkUserAddMember($id);
        return view('admin.project.addmember', compact(['user', 'id','check_member']));
    }

    public function createMember(Request $request)
    {

        //todo get project
        $project = $this->projectRepository->find($request->get('project_id'));
        $arrUser = $request->get('arrUser');

        //insert
        foreach ($arrUser as $key => $item) {
            $addMember = $this->projectItemRepository->create([
                'u_id' => $item,
                'c_code' => $project->c_code,
                'p_name_item' => $project->pName,
                'pu_Auth' => 1,
                'p_code' => $project->id
            ]);
        }
        return redirect()->route('project.show', ['id' => $project->id]);
    }


    public function UpdateProcess(Request $request)
    {
        //    return $request->get('t_Process');
        $task = TaskM::where('id', $request->get('get_id_task'))
            ->update(['t_Process' => $request->get('t_Process')]);
        return redirect()->back()->with('message', 'Update successfully!');
    }

    /**
     * @param Request $request
     */
    public function destroyProject(Request $request)
    {
        $id = $request->get('id');
        $project = $this->projectRepository->delete($id);
        $project_item = $this->projectItemRepository->findByField('p_code',$id);
        foreach ($project_item as $key => $item) {
            $this->projectItemRepository->delete($item->id);
        }
        return redirect()->back()->with('message', 'Deleted successfully');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function apiCountTaskProject(Request $request)
    {
        $id = $request->get('id');
        $project = $this->projectRepository->find($id);
        if($id)
        {
            $totals = $this->projectRepository->countTaskProject($id);
            $done  = $this->projectRepository->countTaskProjectDone($id);

backend/resources/views/admin/project/addmember.blade.php
@extends('admin.master')

@section('content')
    <div class="row">

        <div class="col-md-12">
            <h1>Add members to the project</h1>
            <div class="card">
                <form action="{{ route('project.createMember') }}" method="POST">
                    @csrf
                    <input type="hidden" name="project_id" value="{{ $id }}">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <h4>All members of your company</h4>
                                <br>
                                <ul class="list-group">
                                    <li class="list-group-item"><input id="checkAll" class="form-check-input"
                                                                       type="checkbox" style="margin-left: 5px"> <span
                                                style="margin-left: 4em">All</span></li>
                                    @foreach ($user as $item)
                                        <li class="list-group-item">
                                            <input name="arrUser[]" class="checkItem form-check-input"  type="checkbox" value="{{ $item->id }}"  style="margin-left: 5px"> <span style="margin-left: 4em" class="text-center">{{ $item->name }} - {{$item->email}}</span></li>
                                    @endforeach
                                </ul>
                            </div>
                            <div class="col-md-4">
                                <h4>Current member</h4>
                                <br>
                                <ul class="list-group">
                                    @foreach ($check_member as $value)
                                        <li class="list-group-item">{{$value->username}} - {{$value->email}}</li>
                                    @endforeach
                                </ul>
                            </div>
                            <div class="col-md-4">
                                <h1></h1>

                            </div>
                        </div>
                    </div>
                    <div class="card-footer ">
                        <div class="row">
                            <div class="col-md-9">
                                <button type="submit" class="btn  btn-info text-center">Add</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        $('#checkAll').click(function () {
            $(':checkbox.checkItem').prop('checked', this.checked);
        });
    </script>
@endsection

backend/resources/views/admin/project/create.blade.php
@extends('admin.master')

@section('content')
    <link rel="stylesheet" href="{{asset('css/bootstrap-multiselect.css')}}">
    @if(session()->has('message'))
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
            <span>{{ session()->get('message') }}</span>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header card-header-rose card-header-icon">
                    <h4 class="card-title">Create Project</h4>
                </div>
                <div class="card-body ">
                    <form class="form-horizontal" action="{{ route("project.store") }}" method="POST"
                          enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong class="text-danger">*</strong> Project
                                name</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="pName" class="form-control" name="pName"
                                           placeholder="Enter Project name"
                                           required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong class="text-danger">*</strong> Company
                                ID</label>
                            <div class="col-md-9">
                                <div class="form-group bmd-form-group">
                                    <select name="c_code" id="c_code" class="form-control">
                                        @foreach($company as $value)
                                            <option value="{{$value->id}}">{{$value->c_name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong class="text-danger">*</strong> Member</label>
                            <div class="col-md-9">
                                <div class="form-group bmd-form-group">
                                    <div class="bs-docs-example">
                                        <select class="custom-select" name="arrUser[]" id="basic" required multiple="multiple">
                                            @foreach($user as $value)
                                                <option value="{{$value->id}}">{{$value->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong class="text-danger">*</strong> Project
                                Type</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <select class="form-control" name="pType" id="pType" required>
                                        <option value="large">Large Project</option>
                                        <option value="small">Small Project</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong>&nbsp;</strong> Contents</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                <textarea class="form-control text-left" name="pContents" id="pContents" cols="30"
                                          rows="10" placeholder="Enter Content..."></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong class="text-danger">*</strong> Amount</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="number" class="form-control" name="pAmount" id="pAmount"
                                           placeholder="Enter Amount..."  maxlength="10"  oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" required/>
                                </div>
                                <div class="form-group has-default bmd-form-group">
                                    <input type="text" class="form-control" id="pAmount_2" style="padding-left: 1em"
                                           readonly/>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-6">
                                <label class=" col-form-label"><strong class="text-danger">*</strong> Date</label>
                                <div class="form-group has-default bmd-form-group">
                                    <input type="text" class="form-control" name="psDate" id="start_date"
                                           placeholder="Select date" required/>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <label class=" col-form-label"><strong class="text-danger">*</strong> To</label>
                                <div class="form-group bmd-form-group is-filled">
                                    <input type="text" class="form-control" name="peDate" id="end_date"
                                           placeholder="Select to" required/>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong>&nbsp;</strong> Attachment</label>
                            <div class="col-md-9">
                                <div>
                                    <input type="file"
                                           accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel,application/pdf,application/vnd.ms-excel,image/png, image/jpeg"
                                           class="form-control" name="a_code" id="a_code"/>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="card-footer ">
                            <div class="row">
                                <div class="col-md-9">
                                    <button type="submit" class="btn btn-info btn-register">Create</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{{asset('js/bootstrap-multiselect.js')}}"></script>
    <script src='{{asset('../assets/js/input-date.js')}}'></script>
    <script>
        $('#basic').multiselect({
            templates: {
                li: '<li><a href="javascript:void(0);"><label class="pl-2"></label></a></li>'
            }
        });

        function commaSeparateNumber(val){
            while (/(\d+)(\d{3})/.test(val.toString())){
                val = val.toString().replace(/(\d+)(\d{3})/, '$1'+','+'$2') ;
            }
            return val+ ' '+ '$';
        }
        $('#pAmount').focusout(function(){

            $("#pAmount_2").val(
                commaSeparateNumber($(this).val())
            );
        });
    </script>
    <script>
        CKEDITOR.replace('pContents',{
            uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json',
            filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
            filebrowserImageBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Images') }}',
            filebrowserFlashBrowseUrl: '{{ asset('ckfinder/ckfinder.html?type=Flash') }}',
            filebrowserUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
            filebrowserImageUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
            filebrowserFlashUploadUrl: '{{ asset('ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}'
        });
        var expanded = false;
    </script>
@endsection

backend/resources/views/admin/project/index.blade.php
@extends('admin.master')

@section('content')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    @if(session()->has('message'))
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
            <span>
        {{ session()->get('message') }}</span>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            @if(Auth::user()->is_Admin === 1)
                <a class="btn btn-info btn-register" href="{{ route('project.create') }}">New Project</a>
            @endif
        </div>
        <br>
        <br>
        <br>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">List Project</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-task">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>{{ trans('message.project_name') }}</th>
                                <th>{{ trans('message.date') }}</th>
                                <th>{{ trans('message.to') }}</th>
                                <th>{{ trans('message.project_type') }}</th>
                                <th>{{ trans('message.amount') }}</th>
                                <th>{{ trans('message.action') }}</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function confirmDelete($id) {
            if (confirm("Are you sure you want to delete this item?") == true) {
                $(document).find('#frm_delete_' + $id).submit();
            } else {
                return false
            }
        }
        $(function () {
            $('#dataTables-task').DataTable({
                async: true,
                ajax: {
                    "url": "{{ route('api.project.showData') }}",
                    "type": "GET",
                    "headers": {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                },
                "order": [[ 0, "desc" ]],
                columns: [
                    {data: 'id',orderable: true},
                    {data: 'pName',searchable: true},
                    {data: 'psDate',orderable: false, searchable: false},
                    {data: 'peDate'},
                    {data: 'pType',orderable: true,searchable: true},
                    {data: 'amount',orderable: true,searchable: true},
                    {data: 'action', name: 'action', orderable: false, searchable: false,class:"text-center"},
                ]
            });
        });
    </script>
@endsection