backend/routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(/**
 *
 */ ['middleware' => ['CheckVeri']], function () {
    Route::get('/', function() {
        return redirect('admin-dashboard');
    });
    Route::get('/admin-dashboard','DashboardController@index')->name('admin-dashboard');
    Route::get('/api-show-task-today','DashboardController@showMyTaskToday');

    Route::resource('/user-profile','UserController');
    Route::resource('/project','ProjectController');

    //project
    Route::get('/add-member/{id}','ProjectController@addMember')->name('project.addMember');
    Route::post('/createMember','ProjectController@createMember')->name('project.createMember');
    Route::get('/project-delete','ProjectController@destroyProject')->name('project-delete');
    Route::get('/api-show-count-project-task','ProjectController@apiCountTaskProject')->name('api-show-count-project-task');
    //download
    Route::post('/download','DownloadController@download')->name('download');

    Route::resource('/project-item','ProjectItemController');

    //task
    Route::resource('/project-task','TaskController');
    Route::get('/my-task','TaskController@myTask')->name('my-task');
    Route::get('/add-member-task/{id}','TaskController@addMember')->name('add-member-task');
    Route::post('/createMemberSubtask','TaskController@createMemberSubTask')->name('createMemberSubTask');
    Route::post('/update-task','AdminTaskController@updateTask')->name('update-task');


    Route::get('/show-task','TaskController@apiShowTask')->name('api.ShowTask');

    Route::post('update-status-task','ProjectController@UpdateProcess')->name('project.update-process-task');

    Route::get('/show-my-task-data','TaskController@showMyTaskData')->name('api.show-my-task-data');

    Route::get('/show-data-project','ProjectController@showData')->name('api.project.showData');

    Route::get('/apiShowDetailTask',"TaskController@apiShowDetailTask")->name('apiShowDetailTask');
    //calendar

    Route::get('/show-calendar-my-task','TaskController@calendarMyTask')->name('show-calendar-my-task');
    Route::get('/api-show-my-task','TaskController@apiShowMyTask')->name('api.ShowMyTask');
    Route::get('/api-search-my-task','TaskController@apiSearchMyTask')->name('api.SearchMyTask');
    Route::get('/search-my-task','TaskController@searchMyTaskCalendar')->name('searchMyTaskCalendar');

    //only admin
    Route::resource('/admin-task','AdminTaskController');
    Route::get('/api-show-all-task','AdminTaskController@showAllTask')->name('api-show-all-task');
    Route::get('/calendar-admin-task','AdminTaskController@calendarTaskAdmin')->name('calendar-admin-task');
    Route::get('/api-show-admin-task','AdminTaskController@apiShowAdminCalendar')->name('api.ShowAdminTask');
    Route::get('/search-calendar-admin','AdminTaskController@searchCalendarAdmin')->name('search.CalendarAdmin');
    Route::get('/show-all-user','UserController@showUser')->name('show-all-user');
    Route::get('/api-task-due-date','AdminTaskController@showTaskDueDate')->name('api-task-due-date');


    //Report
    Route::get('/report','ReportController@index')->name('report.index');
    Route::get('/report-apiShowCountTask','ReportController@apiShowCountTask')->name('report.apiShowCountTask');

    //update task by api
    Route::get('/api-update-task','AdminTaskController@apiUpdateTask')->name('apiUpdateTask');

    //company
    Route::resource('/company','AdminCompanyController');
    Route::get('/show-data-company','AdminCompanyController@showData')->name('show-data-company');
    Route::get('/company-delete','AdminCompanyController@destroyCompany')->name('destroy-company');

    //user
    Route::resource('/admin-user','AdminUserController');
    Route::get('/show-data-user','AdminUserController@showData')->name('show-user-company');
    Route::get('/admin-user-confirm/{id}','AdminUserController@updateUser')->name('updateUser');
    Route::get('/user-delete','AdminUserController@userDelete')->name('user-delete');
    Route::post('/user-delete-all','AdminUserController@userDeleteAll')->name('user-delete-all');
    Route::get('/upgrade-manager/{id}','AdminUserController@upgradeManger')->name('upgrade-manager');
    Route::get('/upgrade-user/{id}','AdminUserController@updateMember')->name('upgrade-user');

    //grant chart
    Route::resource('/grant-chart',"GrantChartController");
    //api grant chart
    Route::get('/api-grant-chart','GrantChartController@apiGrantChart')->name('api-grant-chart');
    Route::get('/search-gantt-chart','GrantChartController@searchGantt')->name('search-gantt-chart');
    Route::get('/api-search-gantt-chart','GrantChartController@apiSearchGanttChart')->name('api-search-gantt-chart');

    //delete sub task
    Route::get('/delete-sub-task/{id}','AdminTaskController@deleteSubTask')->name('delete-sub-task');

    //gantt
    Route::get('/api-pie-chart','AdminChartController@apiPieChart')->name('api-pie-chart');

    //project more
    Route::get('/project-more', function (){return view('admin.project.more');})->name('project.more');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/error-not-verify', function (){
   return view('errors.500');
});

Route::get('change-language/{locale}', 'HomeController@changeLanguage')->name('user.change-language');

Route::post('/uploads-file',function (){
    return "OKKOKOKOK";
});

backend/app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\Eloquent\ProjectEloquentRepository;
use App\Repositories\Eloquent\ProjectItemEloquentRepository;
use App\Repositories\Eloquent\CompanyEloquentRepository;
use App\Repositories\Eloquent\AttachmentEloquentRepository;
use App\Repositories\Eloquent\UserEloquentRepository;
use App\Repositories\Eloquent\TaskEloquentRepository;
use Auth;
use App\Models\Attachment;
use App\Models\TaskLog;
use Yajra\Datatables\Datatables;
use Session;
use App;
use Config;
use Mail;
use App\Jobs\SendMailForDues;
use Carbon\Carbon;

class TaskController extends Controller
{
    private $projectRepository;
    private $projectItemRepository;
    private $companyRepository;
    private $attachmentRepository;
    private $userRepository;
    private $taskRepository;

    function __construct(
        ProjectEloquentRepository $projectRepository,
        CompanyEloquentRepository $companyRepository,
        AttachmentEloquentRepository $attachmentRepository,
        UserEloquentRepository $userRepository,
        ProjectItemEloquentRepository $projectItemRepository,
        TaskEloquentRepository $taskRepository
    )
    {
        $this->projectRepository = $projectRepository;
        $this->companyRepository = $companyRepository;
        $this->attachmentRepository = $attachmentRepository;
        $this->userRepository = $userRepository;
        $this->projectItemRepository = $projectItemRepository;
        $this->taskRepository = $taskRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    public function showMyTaskData(Request $request)
    {
        $id = Auth::user()->id;
        $task = $this->taskRepository->showMyTask($id);
        $encrypter = app('Illuminate\Encryption\Encrypter');
        $token = $encrypter->encrypt(csrf_token());
        // return $token;
        return Datatables::of($task)
            ->addColumn('action', function ($task) use ($token) {
                return '
                 <a class="btn btn-sm btn-info btn-round btn-register btn_center" href="/project-task/' . $task->id . '"> <i class="fas fa-eye"></i></a>
                ';
            })
            ->make(true);
    }

    // <a href="/project-task/' . $task->id . '/edit">  <i class="fas fa-edit"></i></a>

    public function apiShowTask(Request $request)
    {
        // return "OK";
        $p_code = $request->get('p_code');
        $assign_to = $request->get('assign_to');
        $task = $this->taskRepository->showTask($p_code, $assign_to);
        return response()->json([
            'code' => 200,
            'data' => $task
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $project = $this->projectRepository->all();
        $company_id = Auth::user()->c_code;
        $user = $this->userRepository->findByField('c_code', $company_id);
        return view('admin.task.create', compact(['project', 'user']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

//        return $request->all();
        $arrUser = $request->get('arrUser');

        $user = Auth::user();
        if ($request->get('arrUser')) {
            foreach ($arrUser as $item) {
                $task = $this->taskRepository->create([
                    'c_code' => $user->c_code,
                    'tSubject' => $request->get('tSubject'),
                    't_sDate' => $request->get('t_sDate'),
                    't_eDate' => $request->get('t_eDate'),
                    't_diff' => $request->get('t_diff'),
                    't_Pred' => $request->get('t_Pred'),
                    't_Contents' => $request->get('t_Contents'),
                    't_Type' => $request->get('t_Type'),
                    't_Process' => $request->get('t_Process'),
                    't_Done' => 0,
                    'parent_id' => null,
                    'assign_to' => $item,
                    'p_code' => $request->get('p_code'),
                    'created_task_name' => Auth::user()->u_nickname
                ]);

            }
            $assign_email = $this->userRepository->findWhereIn('id',$arrUser);
            $email_manager = Auth::user()->email;
            foreach ($assign_email as $value) {
                $data = [
                    'email_member' => $value->email,
                    'email_manager' => $email_manager,
                    'name' => $value->u_nickname,
                    'task_name' => $task->tSubject,
                    'task_id' => $task->id,
                    'assign_by' => Auth::user()->u_nickname,
                ];
//                 dispatch(new SendMailForDues($data))->delay(now()->addMinutes(1));
                $email = $data['email_member'];
                $emailManager = $data['email_member'];
                Mail::send(/**
                 * @param $message
                 */ 'admin.mail.newtask', array(
                    'email' => $data['email_member'],
                    'name' => $data['name'],
                    'task_name' => $data['task_name'],
                    'assign_by' => $data['assign_by'],
                    'task_id' => $data['task_id'],
                ), function ($message)use($email,$email_manager) {
                    $message->to($email, 'NEW TASK')->subject('You has new Task!');
                });
            }


        } else {
            $task = $this->taskRepository->create([
                'c_code' => $user->c_code,
                'tSubject' => $request->get('tSubject'),
                't_sDate' => $request->get('t_sDate'),
                't_eDate' => $request->get('t_eDate'),
                't_diff' => $request->get('t_diff'),
                't_Pred' => $request->get('t_Pred'),
                't_Contents' => $request->get('t_Contents'),
                't_Type' => $request->get('t_Type'),
                't_Process' => $request->get('t_Process'),
                't_Done' => 0,
                'parent_id' => null,
                'assign_to' => null,
                'p_code' => $request->get('p_code'),
                'created_task_name' => Auth::user()->u_nickname
            ]);
        }
        //upload attachment file
        if ($request->hasFile('a_code')) {
            $excel = $request->file('a_code')->store('public/documents');
            $url_excel = $excel;
            $attachment = Attachment::create([
                'c_code' => $user->c_code,
                't_code' => $task->id,
                'a_file' => $url_excel,
                'a_fileName' => $request->file('a_code')->getClientOriginalName(),
                'a_date' => date("Y-m-d"),
                'user_id' => $user->id
            ]);
        }
        return redirect()->back()->with('message', 'Create successful!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = $this->taskRepository->showTaskID($id);
        $sub_task = $this->taskRepository->subTask($id);
        $attachment = $this->attachmentRepository->findByField('t_code', $id);
//        return $task;
        $log = TaskLog::where('t_code', $id)->orderBy('created_at', 'desc')->limit(10)->get();
        return view('admin.task.show', compact(['task', 'log', 'id', 'sub_task', 'attachment']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tasks = $this->taskRepository->showTaskID($id);
        $projectID = '';
        foreach ($tasks as $t)
        {
            $projectID = $t->p_code;
        }
        $project = $this->projectRepository->all();
        $user = $this->taskRepository->showUserInTaskUpdate($projectID);
//        return $user;
        return view('admin.task.edit', compact(['id', 'project', 'user', 'tasks']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // return $request->all();
        $user = Auth::user();
        // luu vao commit
        $task_id = $this->taskRepository->find($id);
         $user_task = $this->userRepository->find($task_id->assign_to);
        //log
        $task_commit = TaskLog::create([
            't_code' => $id,
            'l_status' => "Updated by: " . '<span class="text-info">' . $user->u_nickname . '</span>' . " about: " . '<span class="text-info">' . date('Y-m-d H:i:s') . '</span>' . " ago ",
            'l_content' => $request->get('task_commit'),
            'l_user_id' => $request->get('assign_to'),
            'time_log' => date('Y-m-d H:i:s')
        ]);
        //update task
        $task = $this->taskRepository->update($request->all(), $id);
        $email = $user_task->email;
        //send mail
        Mail::send(/**
         * @param $message
         */ 'admin.mail.updateTask', array(
             'id' => $task_id->id,
            'email' => $user_task->email,
            'name' => $user_task->u_nickname,
            'task_name' => $task_id->tSubject,
            'change_by' => $user->name ,
            'content' => "Updated by: " . '<span class="text-info">' . $user->u_nickname . '</span>' . " about: " . '<span class="text-info">' . date('Y-m-d H:i:s') . '</span>' . " ago ",
        ), function ($message)use($email) {
            $message->to($email, 'TASK UPDATE')->subject('The task assigned to you has new updates!');

backend/resources/views/admin/task/index.blade.php
@extends('admin.master')

@section('content')
<link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script src='{{asset('../assets/js/admin.js')}}'></script>
<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active " href="{{route('admin-task.index')}}">Task List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-danger" href="{{route('calendar-admin-task')}}">Calendar</a>
            </li>
        </ul>

    </div>
</div>
<br>
<br>
<div class="row">
    <div class="col-md-12">
            @if(Auth::user()->is_Admin === 1)
            <a class="btn btn-info" href="{{route('calendar-admin-task')}}">New Task</a>
            @endif
    </div>
     <br>
     <br>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">Task List</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-task">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th>Title</th>
                            <th>Created</th>
                            <th>Assign to</th>
                            <th>Date</th>
                            <th>To</th>
                            <th>% Done</th>
                            <th>Level</th>
                            <th>Process</th>
                            <th>Task type</th>
                            <th>Project name</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{{--    //modal--}}
<div class="modal" tabindex="-1" role="dialog" id="Task_detail">
    <div class="modal-dialog modal-xl" id="Task_detail_closed" role="document">
        <div class="modal-content">
            <form action="{{route('update-task')}}" method="post">
                @csrf
                <input type="hidden" name="id" id="id" value="">
                <div class="modal-header">
                    <div class="col-md-10">
                        <h5 class="modal-title" id="modal-title">Task -  </h5>
                    </div>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="wait2"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <nav>
                                <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                                    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab"
                                       href="#nav-home" role="tab" aria-controls="nav-home"
                                       aria-selected="true"><strong class="text-justify">Task</strong></a>
                                    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab"
                                       href="#nav-profile" role="tab" aria-controls="nav-profile"
                                       aria-selected="false"><strong class="text-justify">SubTasks</strong></a>
                                    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab"
                                       href="#nav-contact" role="tab" aria-controls="nav-contact"
                                       aria-selected="false"><strong class="text-justify">Task Logs</strong></a>
                                </div>
                            </nav>
                            <div class="tab-content" id="nav-tabContent">
                                <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                                     aria-labelledby="nav-home-tab">
                                    <table class="table" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Process</th>
                                            <th>Task type</th>
                                            <th>% Done</th>
                                            <th>Project name</th>
                                            <th>Assign</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><span id="title"></span></td>
                                            <td id="process"></td>
                                            <td id="t_task_type"></td>
                                            <td id="tabel_done"></td>
                                            <td id="project_name"></td>
                                            <td id="assign_name"></td>
                                            <td id="url"></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <hr>
                                    <br>
                                    <h3># Update Task</h3>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="">Assign to</label>
                                                <select name="assign_to" id="assign_user" class="form-control">
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for=""> % Done</label>
                                                <select name="t_Done" id="t_Done" class="form-control">

                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="">Process</label>
                                                <select name="t_Process" id="t_Process" class="form-control"
                                                        required>

                                                </select>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for=""><strong class="text-danger">*</strong> Note</label>
                                                <textarea name="task_commit" id="" class="form-control" cols="30"
                                                          rows="10" required></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        @if(Auth::user()->is_Admin === 1)
                                            <div class="col-md-6">
                                                <a  id="delete" style="margin-left: 1em"></a> <a  id="create_sub_task" style="float: left;text-align: right;"></a>
                                            </div>
                                            <div class="col-md-6 text-right">
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        @else
                                            <div class="col-md-12 text-right">
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        @endif
                                    </div>

                                </div>
                                <div class="tab-pane fade" id="nav-profile" role="tabpanel"
                                     aria-labelledby="nav-profile-tab">

                                    <table class="table" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Date</th>
                                            <th>To</th>
                                            <th>Assign</th>
                                            <th>% Done</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody id="sub_task">

                                        </tbody>
                                    </table>
                                    <br>
                                    <hr>

                                </div>
                                <div class="tab-pane fade" id="nav-contact" role="tabpanel"
                                     aria-labelledby="nav-contact-tab">
                                    <ul class="list-group" id="logs">

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">


                </div>
            </form>
        </div>
    </div>

</div>
<script>
    function confirmDelete($id) {
        if (confirm("Are you sure you want to delete this item?") == true) {
            $(document).find('#frm_delete_' + $id).submit();
        } else {
            return false
        }
    }
</script>
@endsection