backend/routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::group(/**
 *
 */ ['middleware' => ['CheckVeri']], function () {
    Route::get('/', function() {
        return redirect('admin-dashboard');
    });
    Route::get('/admin-dashboard','DashboardController@index')->name('admin-dashboard');
    Route::get('/api-show-task-today','DashboardController@showMyTaskToday');

    Route::resource('/user-profile','UserController');
    Route::resource('/project','ProjectController');

    //project
    Route::get('/add-member/{id}','ProjectController@addMember')->name('project.addMember');
    Route::post('/createMember','ProjectController@createMember')->name('project.createMember');
    Route::get('/project-delete','ProjectController@destroyProject')->name('project-delete');
    Route::get('/api-show-count-project-task','ProjectController@apiCountTaskProject')->name('api-show-count-project-task');
    //download
    Route::post('/download','DownloadController@download')->name('download');

    Route::resource('/project-item','ProjectItemController');

    //task
    Route::resource('/project-task','TaskController');
    Route::get('/my-task','TaskController@myTask')->name('my-task');
    Route::get('/add-member-task/{id}','TaskController@addMember')->name('add-member-task');
    Route::post('/createMemberSubtask','TaskController@createMemberSubTask')->name('createMemberSubTask');
    Route::post('/update-task','AdminTaskController@updateTask')->name('update-task');


    Route::get('/show-task','TaskController@apiShowTask')->name('api.ShowTask');

    Route::post('update-status-task','ProjectController@UpdateProcess')->name('project.update-process-task');

    Route::get('/show-my-task-data','TaskController@showMyTaskData')->name('api.show-my-task-data');

    Route::get('/show-data-project','ProjectController@showData')->name('api.project.showData');

    Route::get('/apiShowDetailTask',"TaskController@apiShowDetailTask")->name('apiShowDetailTask');
    //calendar

    Route::get('/show-calendar-my-task','TaskController@calendarMyTask')->name('show-calendar-my-task');
    Route::get('/api-show-my-task','TaskController@apiShowMyTask')->name('api.ShowMyTask');
    Route::get('/api-search-my-task','TaskController@apiSearchMyTask')->name('api.SearchMyTask');
    Route::get('/search-my-task','TaskController@searchMyTaskCalendar')->name('searchMyTaskCalendar');

    //only admin
    Route::resource('/admin-task','AdminTaskController');
    Route::get('/api-show-all-task','AdminTaskController@showAllTask')->name('api-show-all-task');
    Route::get('/calendar-admin-task','AdminTaskController@calendarTaskAdmin')->name('calendar-admin-task');
    Route::get('/api-show-admin-task','AdminTaskController@apiShowAdminCalendar')->name('api.ShowAdminTask');
    Route::get('/search-calendar-admin','AdminTaskController@searchCalendarAdmin')->name('search.CalendarAdmin');
    Route::get('/show-all-user','UserController@showUser')->name('show-all-user');
    Route::get('/api-task-due-date','AdminTaskController@showTaskDueDate')->name('api-task-due-date');


    //Report
    Route::get('/report','ReportController@index')->name('report.index');
    Route::get('/report-apiShowCountTask','ReportController@apiShowCountTask')->name('report.apiShowCountTask');

    //update task by api
    Route::get('/api-update-task','AdminTaskController@apiUpdateTask')->name('apiUpdateTask');

    //company
    Route::resource('/company','AdminCompanyController');
    Route::get('/show-data-company','AdminCompanyController@showData')->name('show-data-company');
    Route::get('/company-delete','AdminCompanyController@destroyCompany')->name('destroy-company');

    //user
    Route::resource('/admin-user','AdminUserController');
    Route::get('/show-data-user','AdminUserController@showData')->name('show-user-company');
    Route::get('/admin-user-confirm/{id}','AdminUserController@updateUser')->name('updateUser');
    Route::get('/user-delete','AdminUserController@userDelete')->name('user-delete');
    Route::post('/user-delete-all','AdminUserController@userDeleteAll')->name('user-delete-all');
    Route::get('/upgrade-manager/{id}','AdminUserController@upgradeManger')->name('upgrade-manager');
    Route::get('/upgrade-user/{id}','AdminUserController@updateMember')->name('upgrade-user');

    //grant chart
    Route::resource('/grant-chart',"GrantChartController");
    //api grant chart
    Route::get('/api-grant-chart','GrantChartController@apiGrantChart')->name('api-grant-chart');
    Route::get('/search-gantt-chart','GrantChartController@searchGantt')->name('search-gantt-chart');
    Route::get('/api-search-gantt-chart','GrantChartController@apiSearchGanttChart')->name('api-search-gantt-chart');

    //delete sub task
    Route::get('/delete-sub-task/{id}','AdminTaskController@deleteSubTask')->name('delete-sub-task');

    //gantt
    Route::get('/api-pie-chart','AdminChartController@apiPieChart')->name('api-pie-chart');

    //project more
    Route::get('/project-more', function (){return view('admin.project.more');})->name('project.more');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/error-not-verify', function (){
   return view('errors.500');
});

Route::get('change-language/{locale}', 'HomeController@changeLanguage')->name('user.change-language');

Route::post('/uploads-file',function (){
    return "OKKOKOKOK";
});

backend/app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'c_name',
        'c_tel',
        'c_email',
        'c_id'
    ];
}

backend/app/Http/Controllers/Api/CompanyController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Eloquent\CompanyEloquentRepository;

class CompanyController extends Controller
{

    private $companyRepository;

    function __construct(
        CompanyEloquentRepository $companyRepository
    )
    {
//         parent::__construct();
        $this->companyRepository = $companyRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = $this->companyRepository->all();
        if($company) {
            return response()->json([
                    'code'  => '200',
                    'data'=> $company
                ]
            );
        }else {
            return response()->json([
                    'code'  => '400',
                    'data'=> ''
                ]
            );
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

backend/resources/views/admin/company/create.blade.php
@extends('admin.master')

@section('content')
    @if(session()->has('message'))
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
            <span>{{ session()->get('message') }}</span>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header card-header-rose card-header-icon">
                    <h4 class="card-title">Create Company</h4>
                </div>
                <div class="card-body ">
                    <form class="form-horizontal" action="{{ route("company.store") }}" method="POST"
                          enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong class="text-danger">*</strong>Company name</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="text" class="form-control" name="c_name"
                                           placeholder="Name..." required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label">Tel</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="text" class="form-control" name="c_tel" placeholder="Tel..." >
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label">Email</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="email" class="form-control" name="c_email" placeholder="Email...">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <div class="row">
                                <div class="col-md-9">
                                    <button type="submit" class="btn btn-info">Create</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

backend/resources/views/admin/company/edit.blade.php
@extends('admin.master')

@section('content')
    @if(session()->has('message'))
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
            <span>{{ session()->get('message') }}</span>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header card-header-rose card-header-icon">
                    <h4 class="card-title">Update Company</h4>
                </div>
                <div class="card-body ">
                    <form class="form-horizontal" action="{{ route("company.update",['id'=>$company->id]) }}" method="POST"
                          enctype="multipart/form-data">
                        @csrf
                        {{ method_field('PUT') }}
                        <div class="row">
                            <label class="col-md-3 col-form-label"><strong class="text-danger">*</strong> Company name</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="text" class="form-control" name="c_name" value="{{$company->c_name}}" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label">Tel</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="text" class="form-control" name="c_tel" value="{{$company->c_tel}}" >
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label">Email</label>
                            <div class="col-md-9">
                                <div class="form-group has-default bmd-form-group">
                                    <input type="email" class="form-control" name="c_email" value="{{$company->c_email}}">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <div class="row">
                                <div class="col-md-9">
                                    <button type="submit" class="btn btn-info">Update</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

backend/resources/views/admin/company/index.blade.php
@extends('admin.master')

@section('content')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    @if(session()->has('message'))
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
            </button>
            <span>
        {{ session()->get('message') }}</span>
        </div>
    @endif
    <div class="row">
        <div class="col-md-12">
                <a class="btn btn-info" href="{{ route('company.create') }}">New Company</a>
        </div>
        <br>
        <br>
        <br>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Company List</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-task">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name </th>
                                <th>Tel</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function confirmDelete($id) {
            if (confirm("Are you sure you want to delete this item?") == true) {
                $(document).find('#frm_delete_' + $id).submit();
            } else {
                return false
            }
        }
        $(function () {
            $('#dataTables-task').DataTable({
                async: true,
                ajax: {
                    "url": "{{ route('show-data-company') }}",
                    "type": "GET",
                    "headers": {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                },
                columns: [
                    {data: 'id',orderable: true},
                    {data: 'c_name',searchable: true},
                    {data: 'c_tel',orderable: false, searchable: false},
                    {data: 'c_email',orderable: false, searchable: false},
                    {data: 'action', name: 'action', orderable: false, searchable: false,class:"text-center"},
                ]
            });
        });
    </script>
@endsection